/**
 *    This file was auto generated by angular schematics.
 *
 *    For update use script from package.json
 */

export interface ColorData {
  type: 'color' | 'box-shadow' | 'none';
  rgba?: string;
  hex?: string;
  r?: number;
  g?: number;
  b?: number;
  a?: number;
  boxShadowParams?: string[];
}

export interface ColorsMap {
  /** as theme map variable danger-color */
  dangerColor: ColorData;

  /** as theme map variable success-color */
  successColor: ColorData;

  /** as theme map variable warning-color */
  warningColor: ColorData;

  /** as theme map variable bg-color */
  bgColor: ColorData;

  /** as theme map variable bg-main-color */
  bgMainColor: ColorData;

  /** as theme map variable bg-block-main-color */
  bgBlockMainColor: ColorData;

  /** as theme map variable bg-block-0-color */
  bgBlock0Color: ColorData;

  /** as theme map variable bg-block-1-color */
  bgBlock1Color: ColorData;

  /** as theme map variable bg-block-empty-color */
  bgBlockEmptyColor: ColorData;

  /** as theme map variable bg-toggle-color */
  bgToggleColor: ColorData;

  /** as theme map variable bg-toggle-checked-color */
  bgToggleCheckedColor: ColorData;

  /** as theme map variable text-color */
  textColor: ColorData;

  /** as theme map variable text-main-color */
  textMainColor: ColorData;

  /** as theme map variable text-inverse-color */
  textInverseColor: ColorData;

  /** as theme map variable text-static-color */
  textStaticColor: ColorData;

  /** as theme map variable text-link-color */
  textLinkColor: ColorData;

  /** as theme map variable field-focused-color */
  fieldFocusedColor: ColorData;

  /** as theme map variable border-color */
  borderColor: ColorData;

  /** as theme map variable shadow-color */
  shadowColor: ColorData;

  /** as theme map variable box-shadow */
  boxShadow: ColorData;

  /** as theme map variable early-redemption-color */
  earlyRedemptionColor: ColorData;

  /** as theme map variable dot-color-0 */
  dotColor0: ColorData;

  /** as theme map variable dot-color-1 */
  dotColor1: ColorData;

  /** as theme map variable line-color-0 */
  lineColor0: ColorData;

  /** as theme map variable line-color-1 */
  lineColor1: ColorData;

  /** as theme map variable line-color-2 */
  lineColor2: ColorData;

  /** as theme map variable line-color-3 */
  lineColor3: ColorData;

  /** as theme map variable line-color-4 */
  lineColor4: ColorData;

  /** as theme map variable line-color-5 */
  lineColor5: ColorData;

  /** as theme map variable line-color-6 */
  lineColor6: ColorData;

  /** as theme map variable line-color-7 */
  lineColor7: ColorData;

  /** as theme map variable line-color-8 */
  lineColor8: ColorData;

  /** as theme map variable line-color-9 */
  lineColor9: ColorData;

  /** as theme map variable line-color-10 */
  lineColor10: ColorData;

  /** as theme map variable line-color-11 */
  lineColor11: ColorData;

  /** as theme map variable line-color-12 */
  lineColor12: ColorData;

  /** as theme map variable line-color-13 */
  lineColor13: ColorData;

  /** as theme map variable line-color-14 */
  lineColor14: ColorData;

  /** as theme map variable line-color-15 */
  lineColor15: ColorData;

  /** as theme map variable line-color-16 */
  lineColor16: ColorData;

  /** as theme map variable line-color-17 */
  lineColor17: ColorData;

  /** as theme map variable line-color-18 */
  lineColor18: ColorData;

  /** as theme map variable line-color-19 */
  lineColor19: ColorData;

  /** as theme map variable line-color-20 */
  lineColor20: ColorData;

  /** as theme map variable line-color-21 */
  lineColor21: ColorData;

  /** as theme map variable line-color-22 */
  lineColor22: ColorData;

  /** as theme map variable pie-color-0 */
  pieColor0: ColorData;

  /** as theme map variable pie-color-1 */
  pieColor1: ColorData;

  /** as theme map variable pie-color-2 */
  pieColor2: ColorData;

  /** as theme map variable pie-color-3 */
  pieColor3: ColorData;

  /** as theme map variable pie-color-4 */
  pieColor4: ColorData;

  /** as theme map variable pie-color-5 */
  pieColor5: ColorData;

  /** as theme map variable pie-color-6 */
  pieColor6: ColorData;

  /** as theme map variable pie-color-7 */
  pieColor7: ColorData;

  /** as theme map variable pie-color-8 */
  pieColor8: ColorData;

  /** as theme map variable pie-color-9 */
  pieColor9: ColorData;

  /** as theme map variable default-region-color */
  defaultRegionColor: ColorData;

  /** as theme map variable australia-color */
  australiaColor: ColorData;

  /** as theme map variable russia-color */
  russiaColor: ColorData;

  /** as theme map variable europe-color */
  europeColor: ColorData;

  /** as theme map variable asia-color */
  asiaColor: ColorData;

  /** as theme map variable africa-color */
  africaColor: ColorData;

  /** as theme map variable canada-color */
  canadaColor: ColorData;

  /** as theme map variable mexico-color */
  mexicoColor: ColorData;

  /** as theme map variable usa-color */
  usaColor: ColorData;

  /** as theme map variable south-america-color */
  southAmericaColor: ColorData;
}
